"""Migrate to Supabase

Revision ID: 913e8375e65e
Revises: c7ccdb92a687
Create Date: 2025-01-23 08:27:39.478624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '913e8375e65e'
down_revision: Union[str, None] = 'c7ccdb92a687'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
